### PR TITLE
deps: remove mongoose

### PR DESCRIPTION
**Pull request by nnyyxxxx**
cc https://github.com/The-OSS-Everything-Bot/the-oss-everything-bot/pull/11#pullrequestreview-2513798992

## changes
- uses libsql and redis
- stripped out mongoose and related code
- added migrations sys with users table
- added local.db to .gitignore
- updated warnings.js and warn.js to use new databases instead of mongoose
- added placeable database URLs to .env e.g:
```
REDIS_URL=redis://localhost:6379
LIBSQL_URL=file:local.db
LIBSQL_AUTH_TOKEN=your_token_if_using_remote_libsql
```

before bot shutdown:
image
after bot shutdown:
image
warn persists

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
there is still code referencing mongoose

e.g. warn cmd, server.js, user.js, etc

@OmarIsADev feel free to make edits

**Review by OmarIsADev — APPROVED** [review]

**Comment by OmarIsADev** [comment]
Can you contact me on discord later today? Send me friend request: omarisadev

**Review by awfixer — APPROVED** [review]
we will keep this PR open to make sure we do not hit this bug (wrong word?) again

**Comment by nnyyxxxx** [comment]
bot builds, mongoose has been stripped, more information is in PR description.

review please

**Review by awfixer — APPROVED** [review]

**Pull request merged**
